version: "3.9"

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: equity-trading-timescaledb
    restart: unless-stopped

    ports:
      - "5435:5432" # avoid clashing with local postgres
    
    env_file:
      - ./.dbenv


    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

    command: >
      postgres
      -c shared_preload_libraries=timescaledb
      -c timescaledb.telemetry_level=off

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trader -d trading"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image : redis/redis-stack:latest
    container_name : equity-trading-redisstack
    restart : unless-stopped
    ports : 
      - "6379:6379"
      - "8001:8001"
    
    volumes :
      - redisdata:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro

    command: ["redis-stack-server", "/usr/local/etc/redis/redis.conf"]
    
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata:
  redisdata:
