version: "3.9"

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: equity-trading-timescaledb
    restart: unless-stopped

    ports:
      - "5435:5432" # avoid clashing with local postgres
    
    env_file:
      - ./.dbenv


    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

    command: >
      postgres
      -c shared_preload_libraries=timescaledb
      -c timescaledb.telemetry_level=off

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trader -d trading"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
