
# appendonly yes
appendfsync everysec

# Also keep periodic snapshots (optional)
save 900 1
save 300 10
save 60 10000

protected-mode yes
port 6379
# bind 0.0.0.0  # uncomment only if you need external access beyond localhost

tcp-keepalive 300
maxmemory 512mb
maxmemory-policy allkeys-lru
